### PR TITLE
Fixes #12: Add songs for "When the sun goes down"

### LINKED ISSUE #12: Link song names to YouTube for "When the Sun Goes Down"
Comment a working link as well.

### PR DESCRIPTION
**Pull request by ankichd11**
i have added links to the songs of album "When the sun goes down"

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@ankichd11 Please go through [readme](https://github.com/OrionStar25/Selena-Gomez-Discography/blob/master/README.md) of this project so that you follow the guidelines set by the mentor about PR title and description. Also refer to [this](https://github.com/opencodeiiita/Opencode-Collaborative-19#guidelines-and-best-practices). 😄 
PR will be reviewed by the mentor. Happy coding. ✌️

**Comment by OrionStar25** [comment]
@ankichd11 You do n't have to change the filename. You have to change the PR title as:
Solves #IssueNumber, and then write a description of what you've solved along with a deployed link of your changes.
You also have merge conflicts. You have to update your fork first. Check this out: https://help.github.com/articles/syncing-a-fork/

**Review by OrionStar25 — CHANGES_REQUESTED** [review]
Your code is correct, but you need to update your fork to remove merge conflicts. Do this and your PR will be merged soon. :)

**Comment by OrionStar25** [comment]
@ankichd11 you don't have to change the filename. Please change it back to `index.html`. I was talking about changing the PR title. Please ask for help if you're stuck.

**Comment by ankichd11** [comment]
i am not getting any clue

**Comment by OrionStar25** [comment]
Alright. 
1. [Revert back your commits.](https://stackoverflow.com/questions/1463340/how-to-revert-multiple-git-commits)
2. Get your fork in [sync](https://help.github.com/articles/syncing-a-fork/) with the original repo.
3. Make your changes to `index.html`
4. Send a PR.

**Comment by Divy123** [comment]
@ankichd11 please go through this link. This may help you.
[https://help.github.com/articles/creating-a-pull-request/](url)

**Comment by Divy123** [comment]
@OrionStar25 I think there needs to be a proper instruction set regarding the workflow of sending a PR.
Should we add it to readme?

**Comment by OrionStar25** [comment]
@Divy123 Feel free to suggest any changes to the current readme

**Comment by OrionStar25** [comment]
I'm closing this PR for inactivity.

**Pull request closed without merging**
