### PR TITLE
Added new Movie section 

### PR DESCRIPTION
**Pull request by LalitSharma7**
issue #43 

i am attaching the screenshots for the changes

### CODE REVIEW

**Comment by LalitSharma7** [comment]
screenshot 46
screenshot 48

screenshot 47

**Comment by LalitSharma7** [comment]
Let me know if more changes are required

**Review by OrionStar25 — APPROVED** [review]
Nice work! :1st_place_medal:

**Comment by LalitSharma7** [comment]
Thanks

**Pull request merged**
