### PR TITLE
Fixes #42(album songs should overlap album tiles)

### LINKED ISSUE #42: Album songs should overlap the album tiles on hover
In mobile and Ipad view, albums names are currently hidden behind tiles. They should be above the tiles.

### PR DESCRIPTION
**Pull request by Archies11**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

>Yes
### Solves which issue ?

>Solves #42
### Paste the live website link:

>https://archies11.github.io/Selena-Gomez-Discography/
### Give discription.

>I have made changes as required so that the album songs list overlaps the album tiles.

### CODE REVIEW

**Comment by Archies11** [comment]
Please help me, I tried the z-index prop on the dropdown menu but I am unable to understand where I am going wrong.
Is there a link that might help me?

**Review by OrionStar25 — CHANGES_REQUESTED** [review]
Alright, so few things you can try:
1. change the `z index` of the `image`.
2. This wasn't an issue before the scrolls to the `drop downs` were added. So you can tinker something there to at least show the song list in mobile view.
3. Add `javascript` to overlap image on hover (but i dont think this is that complicated)

**Comment by Archies11** [comment]
I did make some changes to assign z-index values to the album tiles as well as the album headings but the issue persists. As for the changes that might be made in the scroll bar of the dropdown, I am not sure which properties should be altered... :sweat_smile:

**Comment by thenullterminator** [comment]
Can I try?

**Comment by OrionStar25** [comment]
@pradeepgangwar Please help Sir :stuck_out_tongue_closed_eyes:

**Comment by pradeepgangwar** [comment]
Although not recommended but I found a quick fix for mean time. Here we have `<div class="row">` as the parent element and then we have `<div class="album col-xs-6 col-lg-4"> </div>` as the children where albums are mentioned. 
What we can do is ... we can assign z-index to each of them but in decreasing order as:
`<div class="album col-xs-6 col-lg-4" style="z-index: 200;">`
`<div class="album col-xs-6 col-lg-4" style="z-index: 180;">`

This will fix the problem. I guess we may need some code refactoring to make it work properly. 
CSS is crazy most of the times 😛  (I don't like css personally).

**Comment by Archies11** [comment]
> Although not recommended but I found a quick fix for mean time. Here we have `<div class="row">` as the parent element and then we have `<div class="album col-xs-6 col-lg-4"> </div>` as the children where albums are mentioned.
> What we can do is ... we can assign z-index to each of them but in decreasing order as:
> `<div class="album col-xs-6 col-lg-4" style="z-index: 200;">`
> `<div class="album col-xs-6 col-lg-4" style="z-index: 180;">`
> 
> This will fix the problem. I guess we may need some code refactoring to make it work properly.
> CSS is crazy most of the times 😛 (I don't like css personally).

this worked!! :smile:

**Comment by pradeepgangwar** [comment]
@Archies11 Nice! Pls update this PR.

**Comment by Archies11** [comment]
New puul request opened.

**Pull request closed without merging**
