### PR TITLE
Fixes #52:Fix scroll bar in mobile view 

### LINKED ISSUE #52: Fix scroll bar in mobile view
The scroll bar for album songs doesn't work in mobile view

### PR DESCRIPTION
**Pull request by thenullterminator**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

>Yes
### Solves which issue ?

>Solves #58
### Paste the live website link:

>https://thenullterminator.github.io/Selenav3/
### Give discription.

>In order to fix this issue I thought of eliminating the 'listen' button itself and use the entire album image itself responsive to hover and display dropdown list.

### CODE REVIEW

**Comment by thenullterminator** [comment]
upload1
upload2

**Review by OrionStar25 — CHANGES_REQUESTED** [review]
1. I love the slight round edges to the album tiles, so keep them! :smiley: 
2. I like the concept of having no listen button in mobile view. Seems less cluttered. 
3. But, in desktop mode, listen button seems cleaner. 

So, if you could just remove the listen button in smaller screens, that would be great!

**Comment by OrionStar25** [comment]
screenshot from 2019-01-31 23-10-03
Looks like this in my browser :/

**Comment by thenullterminator** [comment]
How can I do it only for mobile view

**Comment by OrionStar25** [comment]
Its very similar to [this](https://stackoverflow.com/questions/41381264/show-button-only-when-view-is-responsive-mobile-size)

**Comment by thenullterminator** [comment]
Done.
checkout: https://thenullterminator.github.io/selenav4/

**Comment by thenullterminator** [comment]
Resolved conflicts

**Review by OrionStar25 — APPROVED** [review]
Okay, so this issue got solved automatically after #42 . Scroll was disabled due to overlapping of `div` elements. So I will close this PR, but you will get these points since your code is correct! :smile:

**Pull request closed without merging**
