### PR TITLE
Fixes #7 : corrected 2 songs from singles list.

### LINKED ISSUE #7: Add correct soundtrack to songs in Singles list
Choose **any 2 songs** of your choice from the `Singles` list which doesn't have the correct song and add the correct soundtrack for them.

The link doesn't need to change. You have to change the default song in the music player. Right now only one type of song is assigned to each player. Download the song and add it to the player.

### PR DESCRIPTION
**Pull request by barney-stinson**
https://github.com/barney-stinson/Selena-Gomez-Discography

### CODE REVIEW

**Review by OrionStar25 — CHANGES_REQUESTED** [review]
Your change is correct but the link that you're supposed to send should be something like this:
https://barney-stinson.github.io/Selena-Gomez-Discography/
Read [this](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) for help.

**Comment by barney-stinson** [comment]
@OrionStar25  ok

**Comment by barney-stinson** [comment]
done.....
https://barney-stinson.github.io/Selena-Gomez-Discography/

**Review by OrionStar25 — APPROVED** [review]
Great work! :dango:

**Pull request merged**
