### PR TITLE
Fixes #6: Update Singles' list + Added a new song(wolves)

### LINKED ISSUE #6: Update Singles' list
Add all her new songs in the same order in the `Singles` list: **Newer first**

### PR DESCRIPTION
**Pull request by thenullterminator**
LIVE LINK:
  https://thenullterminator.github.io/Selena-Gomez-Discography-master

### CODE REVIEW

**Review by OrionStar25 — CHANGES_REQUESTED** [review]
Great work so far! Just 2 more songs need to be added:
Back To You
Taki Taki
:)

**Comment by thenullterminator** [comment]
Thank you!
I will add those songs. Can I also change some alignment

**Comment by OrionStar25** [comment]
Alignment of?

**Comment by thenullterminator** [comment]
singles and albumns

**Comment by OrionStar25** [comment]
We shall make that another issue. One problem at a time :)

**Comment by thenullterminator** [comment]
Should I make another pull request with changes

**Comment by thenullterminator** [comment]
Changes Done

**Review by OrionStar25 — CHANGES_REQUESTED** [review]
Alright, so you hve merge conflicts because of a change made my a previous PR. :cry:  But its simple to solve.

Make this change:
Replace `<audio controls style="width: 100%;">` this for every song in singles list instead of just `<audio controls>`

**Review by OrionStar25 — APPROVED** [review]
All done here! :smiley:

**Pull request merged**
