### PR TITLE
Fixes issue #60: changed text color

### PR DESCRIPTION
**Pull request by rohith203**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

>Yes
### Solves which issue ?

>Solves #60
### Paste the live website link:

> [link](https://rohith203.github.io/Selena-Gomez-Discography/index.html)
### Give description.

> changed color of h1, h2 and h3 tags so that text is visible against the background. "Movies Section" is changed to "Movies"

### CODE REVIEW

**Comment by OrionStar25** [comment]
Live link please.

**Comment by OrionStar25** [comment]
Next time please comment on the issue otherwise it wont be assigned to you and PR will be closed.

**Comment by rohith203** [comment]
How do I get a "live link"? I am a newbie. Can you please explain?

**Comment by OrionStar25** [comment]
Please do read [this](https://github.com/OrionStar25/Selena-Gomez-Discography/blob/master/README.md)

**Comment by OrionStar25** [comment]
[This](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) too.

**Comment by rohith203** [comment]
Pasted the link in the template.

**Pull request merged**
