### PR TITLE
Redundant ids changed fixes #41

### LINKED ISSUE #41: Change any redundant ids to  a class
There are some instances in the code where the same `id` is being used for multiple elements. Change them into a `class` without changing the functionality.

### PR DESCRIPTION
**Pull request by LalitSharma7**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

>Yes
### Solves which issue ?

>Solves #41 
### Paste the live website link:

>[Paste the link here]
### Give discription.

>[Write Here. Be Specific]
I have changed the redunadant id's . You can check it

### CODE REVIEW

**Comment by LalitSharma7** [comment]
@OrionStar25 take a look now. I think this time it is correct

**Comment by OrionStar25** [comment]
Live link please :3

**Comment by LalitSharma7** [comment]
https://rattlecode17sh.github.io/Selena-Gomez-Discography/

here is the live link. @OrionStar25 check it now

**Comment by OrionStar25** [comment]
Yep works! Responsive issues everytime :cry: Need to make another issue for that.

**Pull request merged**
