### PR TITLE
Fixes #57 : Images are breaking

### LINKED ISSUE #57: Images are breaking
Hotel Transylvania etc, are breaking and not being shown. Fix it.

### PR DESCRIPTION
**Pull request by devgupta2607**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

>Yes
### Solves which issue ?

>Solves #57 
### Paste the live website link:

>https://devgupta2607.github.io/Selena-Gomez-Discography/
### Give discription.

>Images of Hotel Transylvania 1 & 2 are fixed

### CODE REVIEW

**Comment by devgupta2607** [comment]
image

**Comment by devgupta2607** [comment]
conversation is locked. Add me as contributor.

**Comment by devgupta2607** [comment]
Can I add Hotel Transylvania 3 too ?

**Comment by OrionStar25** [comment]
Yeah, you can add Hotel Transylvania 3 too. Good job

**Pull request merged**
