### PR TITLE
Fixes #33 : Add scroll in the dropdown of listen button

### LINKED ISSUE #33: Add scroll in the dropdown of listen button
@OrionStar25 
It is looking weird to scroll full page for selecting any song after hovering listen button .

### PR DESCRIPTION
**Pull request by batra-meghna**
Fixes #33 
https://batra-meghna.github.io/Selena-Gomez-Discography/

### CODE REVIEW

**Review by OrionStar25 — CHANGES_REQUESTED** [review]
You're on the right track. Few changes though:
1. Scroll doesn't work on resizing.
2. It'll be better if you added a scroll bar on the side. Seems more intuitive.

**Comment by batra-meghna** [comment]
@OrionStar25 please review the changes
Added scroll bar on the side
selena gomez

**Review by pradeepgangwar — COMMENTED** [review]
Seems like it works! @OrionStar25 Pls review again.

**Review by OrionStar25 — APPROVED** [review]
Works for desktop and ipad. Great work.

**Pull request merged**
